# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8303a332db729dad74a18107c1b749127cba81e5969f812e8db953166958bf1029af7d83cb63314184882b1b6dd5a4fa681181a7315ae2c1c0ae05e2e27d5c92

test:
  secret_key_base: 8303a332db729dad74a18107c1b749127cba81e5969f812e8db953166958bf1029af7d83cb63314184882b1b6dd5a4fa681181a7315ae2c1c0ae05e2e27d5c92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8303a332db729dad74a18107c1b749127cba81e5969f812e8db953166958bf1029af7d83cb63314184882b1b6dd5a4fa681181a7315ae2c1c0ae05e2e27d5c92
